### ISSUE TITLE
apache/name field has dots stripped out

### ISSUE THREAD

**Issue by hax0rbana-adam** [ansibleguy/sw_zoneminder#2]
**Expected behavior**: When using this playbook and passing in variables such as the apache name, the playbook should use the name without mangling it.

**Actual behavior**: The dots are stripped out of the name.

**Steps to reproduce**: pass in the following variables to the playbook.

```
  vars:
    zoneminder:
      path:
        cache: /var/cache/zoneminder/cache
      timezone: 'America/Chicago'
      apache:
        name: "{{ansible_fqdn}}"
        domain: "{{ansible_fqdn}}"
        ssl:
          path: /etc/letsencrypt/live/{{ansible_fqdn}}
          mode: existing
          bundle: true  # letsencrypt bundles intermediate certs
    zm_site_name: "{{ansible_fqdn}}"
    no_prompts: true
    apache2_certs_path: /etc/letsencrypt/live/{{ansible_fqdn}}
    apache2_keys_path: /etc/letsencrypt/live/{{ansible_fqdn}}
```

The playbook will write out `/etc/apache2/sites-enabled/site_camerasexamplecom.conf` which will have incorrect filenames for the `SSLCertificateKeyFile` and `SSLCertificateFile` configurations. The path **does have** the dots and is correct. It is **only the filename** which strips out the dots. This is relevant because I'm passing in the `ansible_fqdn` for both the apache/ssl/path and the apache/name, so it illustrates that problem is not with the value being passed in, but rather that value being mutilated somewhere in the playbook.

The result is that restarting apache fails because it can not find the SSL key/cert files.

**Workaround**: After the playbook fails, manually correct the filenames and then restart the Apache service. Also, hope that there wasn't anything important in the playbook that didn't get run after the failure. Manually having to intervene kinda defeats the purpose of using Ansible, IMO.

**Additional notes**: The configuration file is also affected by this variable mangling. Instead of creating `/etc/apache2/sites-available/site_cameras.example.com.conf` the playbook creates ``/etc/apache2/sites-available/site_camerasexamplecom.conf`. While this is a perfectly acceptable name for the conf file, including the dots would not only be acceptable but preferred. I mention this because fixing the bug that strips out the dots will also affect this filename. Again, it shouldn't be a problem, but I wanted to raise awareness of the issue.

References:

- comment in the defaults file for the infra_apache repo: https://github.com/ansibleguy/infra_apache/blob/133b17f708d0793dccc4c47da51f6022c4fe0f5e/defaults/main/2_site.yml#L13
- template that sets the filename for the key/cert https://github.com/ansibleguy/infra_apache/blob/133b17f708d0793dccc4c47da51f6022c4fe0f5e/templates/etc/apache2/sites-available/inc/site_https_ssl.j2#L5
- ...which is called from: https://github.com/ansibleguy/infra_apache/blob/133b17f708d0793dccc4c47da51f6022c4fe0f5e/templates/etc/apache2/sites-available/inc/site_https.j2#L16C1-L16C38
- ...which is called from: https://github.com/ansibleguy/infra_apache/blob/133b17f708d0793dccc4c47da51f6022c4fe0f5e/templates/etc/apache2/sites-available/site.conf.j2#L5
